### ISSUE TITLE
part number for sd-card holder?

### ISSUE THREAD

**Issue by TimAtFacture** [adafruit/MicroSD-breakout-board#3]
mind sharing?

**Comment by ashishsk** [comment]
Hi @TimAtFacture, did you manage to find out the part number? I think it might be [693071010811](https://www.mouser.de/ProductDetail/Wurth-Elektronik/693071010811?qs=7gQLVZk5cPniDgiow3734g%3D%3D)

**Comment by TimAtFacture** [comment]
I did not, we ended up spec'ing something similar. Thanks for finding this
