### ISSUE TITLE
Is there a footprint for KiCad?

### ISSUE THREAD

**Issue by cbmeeks** [adafruit/MicroSD-breakout-board#4]
I use KiCad and was wondering if there was an easy way to import this board into it?  I would rather not have to create a custom footprint if I don't have to.

Thanks.

**Comment by evaherrada** [comment]
@cbmeeks I haven't ever used KiCad so I don't actually know if this will work but maybe try doing this: https://support.snapeda.com/en/articles/2911566-how-to-import-sch-brd-into-kicad
